Switched to HTTPS, now I get
Error: reqwest::Error { kind: Request, url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("localhost")), port: Some(16512), path: "/", query: None, fragment: None }, source: hyper::Error(Parse(Version)) }

Maybe wrong TLS version? PEP only suports v1.2