Application starts, but panics. thread 'main' panicked at 'already borrowed: BorrowMutError' The reason seems to be that I'm asking for a mutable reference to the state inside app and then I'm  doing the same inside other components that I'm calling from app.